### local ###

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: user
    password: user
    hikari:
      connection-timeout: 3000
      minimum-idle: 1
      maximum-pool-size: 4
  jpa:
    database: postgresql
    properties:      hibernate:
        format_sql: true  
  jackson:
    serialization:
      fail-on-empty-beans: false
      
logging:  file:
    path: D:\\workspace\\JpaProject\\logs    name: jpa