### local ###

spring:
  datasource:
    url: ENC(Wy2PN4QUcGtMHo2ls8JHBluAxVmfUOx0rwHslZhJD2c1Ep4W/geC2T8jtKBP9ucy)
    username: ENC(cmMyK9SPLuSvgXLPY3gvwA==)
    password: ENC(mX4foxlsEND0fFodhoi3EQ==)
    hikari:
      connection-timeout: 3000
      minimum-idle: 1
      maximum-pool-size: 4
  jpa:
    database: postgresql
    properties:      hibernate:
        format_sql: true  
  jackson:
    serialization:
      fail-on-empty-beans: false
      
logging:  file:
    path: D:\\workspace\\JpaProject\\logs    name: jpa
    
jasypt:
  encryptor:
    bean: jasyptEncryptorDES