### release ###

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: user
    password: user
    hikari:
      connection-timeout: 3000
      minimum-idle: 1
      maximum-pool-size: 4
  jpa:
    database: postgresql
    properties:
      hibernate:
        show_sql: true  
  jackson:
    serialization:
      fail-on-empty-beans: false
      
logging:
  file:
    path: /home/user/logs
    name: jpa